### ISSUE TITLE
ci(lighthouse): wrangler dies mid-pass, failing the gate with CHROME_INTERSTITIAL_ERROR

### ISSUE THREAD

**Issue by BreakableHoodie** [BreakableHoodie/settimesdotca#878]
## Symptom

The `Lighthouse CI` job fails intermittently since #869 pointed it at a wrangler-served app. Not an assertion failure — Lighthouse cannot load the page at all:

```
Run #1...done.
Run #2...done.
Run #3...failed!
  runtimeError: CHROME_INTERSTITIAL_ERROR
  mainDocumentUrl: "chrome-error://chromewebdata/"
  "your test URL (http://localhost:8788/) was redirected to chrome-error://chromewebdata/"
```

`.lighthouseci` ends up empty, so the upload step also warns "No files were found".

Observed on run [32258899872](https://github.com/BreakableHoodie/settimesdotca/actions/runs/32258899872) (job 96087110627), branch `feat/735-gap-suggestions`, 2026-08-19.

## What is NOT the cause

- **Not the 0.90 budget** restored in #872. No assertion ran; collection failed.
- **Not a slow boot.** The env action reported `✓ Server is ready on port 8788! (attempt 1, 4s)` at 13:35:34, and Lighthouse runs #1 and #2 completed fine at 13:35:48 and 13:36:00.

## What it looks like

The server served **two** Lighthouse runs and was unreachable for the **third**, ~27s after the last success. So `wrangler pages dev` either crashed or stopped accepting connections partway through the 3-run pass.

`npx serve dist` (the old harness) is a static file server and had no such failure mode. `wrangler pages dev` runs workerd plus esbuild and is a dev server, not a production one — it is doing far more work per request, including D1 access.

Rough rate: **1 failure in ~10** Lighthouse runs since #869. That is high for a required check.

## Why it still beats the old harness

Worth stating plainly so this is not read as "revert #869": the old static harness produced a **phantom 0.2 CLS** and depressed the score ~0.10 by serving a page with no API — see #854. Measuring the real app is correct. The delivery mechanism is what needs hardening.

## Suggested direction, in order

1. **Get evidence first.** The env action already writes wrangler output to `/tmp/wrangler.log`, but the Lighthouse job never surfaces it. Add an `if: failure()` step that dumps it. Cheap, and the next occurrence explains itself instead of needing another repro.
2. Only then decide between: bumping wrangler's resources, retrying the Lighthouse step once (the env action already retries server boot once, precedent in #625), or reducing `numberOfRuns`.

**Do not reduce `numberOfRuns` as the first move** — three runs is what makes the `optimistic` aggregation meaningful, and cutting it to hide a crash would trade a visible flake for a quieter, worse measurement.

## Owner note

Introduced by #869, which I opened. Filing rather than guessing at a fix without the wrangler log.

**Comment by BreakableHoodie** [comment]
## Diagnosed: wrangler **crashes**, it does not wedge

The diagnostics step from #879 fired on its own PR ([run 32266757116](https://github.com/BreakableHoodie/settimesdotca/actions/runs/32266757116/job/96113013545)) and answered the question outright:

```
listeners on :8788:
State Recv-Q Send-Q Local Address:Port Peer Address:PortProcess   <- header only, zero rows
wrangler/workerd processes:
  none running
HTTP probe:
curl: (7) Failed to connect to localhost port 8788 after 0 ms: Couldn't connect to server
  status=000 time=0.000214s
```

**No wrangler or workerd process survives, nothing is listening, and the connection is refused in 0.2 ms.** That is a dead process, not a hung one — which rules out the "wedged" branch and the fixes that would have followed from it.

## Where it dies

The tail of `/tmp/wrangler.log`, immediately before the end:

```
[wrangler:info] GET /assets/index-DRysnVVK.js 200 OK (19ms)
✘ [ERROR]
Note that there is a newer version of Wrangler available (4.124.0).
Consider checking whether upgrading resolves this error.
```

It dies **mid-asset-serving on run #3**, after handling runs #1 and #2 cleanly. The error message itself is **empty** — wrangler printed an `✘ [ERROR]` with no text — which is why nothing surfaced before this step existed.

Version in CI at the time: **wrangler 4.123.0**. Wrangler's own output suggests 4.124.0 may fix it.

## Candidate fix, in order

1. **Bump wrangler to ≥ 4.124.0** and watch the rate. The tool is self-reporting a newer version against this exact error, it is a one-line dependency change, and it costs nothing to try. Dependabot will likely offer it anyway.
2. If the crash survives the bump, capture more: `--log-level debug` on the dev server, and check runner memory around the crash — an empty `✘ [ERROR]` with an immediate death smells like an OOM or a workerd abort.
3. Only then consider retrying the Lighthouse step.

Still **not** the answer: reducing `numberOfRuns`. Three runs is what makes the `optimistic` aggregation meaningful, and the crash lands on run #3 precisely because it needs a while to happen — cutting to 2 would hide it rather than fix it.

## Note

The step also mis-reported its own listener check on that first run (`ss` prints a header with zero rows, which is non-empty). Fixed in #879 along with a port-matching precision fix. The process and HTTP probes were correct and are what settled the diagnosis.

**Comment by BreakableHoodie** [comment]
## Second occurrence — same signature, and the diagnostics now work

Recurred on #882 ([run 32275377298](https://github.com/BreakableHoodie/settimesdotca/actions/runs/32275377298/job/96141449732)), which is on **wrangler 4.123.0** — it does not carry #880's bump.

```
Run #1...done.
Run #2...done.
Run #3...failed!    CHROME_INTERSTITIAL_ERROR

listeners on :8788:
  none
wrangler/workerd processes:
  none running
HTTP probe:
  curl: (7) Failed to connect ... status=000 time=0.000215s
```

Byte-for-byte the same shape as the first: survives two Lighthouse runs, dies before the third, process gone, connection refused instantly. **Crashed, not wedged** — confirmed twice now, not inferred once.

## Refinement: the death is silent

The first occurrence ended with an empty `✘ [ERROR]` plus wrangler's "newer version available" hint. **This one has no error output at all** — the log just stops mid-asset-serving:

```
[wrangler:info] GET /assets/calendar-days-B7zv-wfc.js 200 OK (11ms)
[wrangler:info] GET /assets/festivalDays-mcP11bFD.js 200 OK (19ms)
<end of log>
```

Both die while serving JS chunks on run #3. An abrupt exit producing no diagnostic fits a **hard abort — OOM or a workerd crash** — rather than any handled error path. That also explains why nothing was ever visible before the diagnostics existed.

## Diagnostics validated in production

Worth recording: the `-H` fix works. The first run printed `ss`'s header row (which reads as "something IS listening"); this run correctly prints `none`. The crashed-vs-wedged distinction is now reliable.

## Where this leaves the fix

**#880 (wrangler 4.123.0 → 4.124.0, workerd 1.20260811.1 → 1.20260815.1) is still the right next probe**, and this occurrence is mild evidence for it: the crash reproduces on the un-bumped version, while #880's own CI has now passed Lighthouse twice on the bumped one.

That is **not** proof — two passes against a ~1-in-10 flake is well within chance. But it is the cheapest available lever, and the instrumentation is now good enough to judge the result over a handful of runs.

If it survives the bump, the next probe is memory: capture `free -m` / dmesg around the crash, since a silent abort mid-asset-serving is what an OOM kill looks like.

**Comment by BreakableHoodie** [comment]
## Third occurrence — on 4.124.0. The bump did not fix it.

Recurred on #885 ([run 32289601137](https://github.com/BreakableHoodie/settimesdotca/actions/runs/32289601137/job/96187098856)), which carries #880's bump:

```
⛅️ wrangler 4.124.0
Run #1...done.  Run #2...done.  Run #3...failed!
CHROME_INTERSTITIAL_ERROR
listeners on :8788:      none
wrangler/workerd:        none running
HTTP probe:              status=000 time=0.000162s
last request:            GET /assets/plus-DUNf9PmK.js 200 OK (38ms)   <end of log>
```

**The version hypothesis is spent.** wrangler's own *"Consider checking whether upgrading resolves this error"* was a red herring — and the empty `✘ [ERROR]` line that carried it appears in only **one of the three** occurrences, so it was incidental rather than diagnostic.

Worth recording so the evidence is not misread later: **#880 passed Lighthouse twice on 4.124.0 before this failure.** That is exactly what a ~1-in-10 flake looks like, and why #880's description said a green run would prove nothing. Two passes were never evidence of a fix.

## What three occurrences now agree on

| Observation | What it rules out |
|---|---|
| Always run **#3**, never #1 or #2 | needs sustained load to trigger |
| Every request `200 OK` at normal timings right to the end | gradual degradation / resource creep |
| Process **gone**, port refused in ~0.2 ms | a hang or wedged server |
| No error output in 2 of 3 | a handled error path |

Healthy right up to an instantaneous silent exit. That is an **abort**, and the two live candidates need different responses:

- **kernel OOM kill** → give workerd headroom, or reduce concurrent load during the pass
- **workerd crash** → reproduce minimally and report upstream

Nothing captured so far can tell them apart.

## Next probe

#887 adds `free -m`, `/proc/loadavg` and a `dmesg` OOM scan to the existing `if: failure()` step. That is the specific question three runs have failed to answer.

If the next occurrence shows an OOM kill, the fix is resource-side. If it shows none — with `dmesg` readable — then workerd is aborting on its own and this becomes an upstream bug report with a clean reproduction: *dies on the third consecutive Lighthouse pass, mid-asset-serving, no output.*

## Not worth doing yet

Reducing `numberOfRuns` to 2 would make the symptom disappear without explaining it — the crash lands on run #3 precisely because it needs the accumulated load. That would trade a visible flake for a quieter, weaker measurement.

**Comment by BreakableHoodie** [comment]
## Fourth occurrence — and the memory probes rule out OOM

Recurred on #887 ([run 32295262333](https://github.com/BreakableHoodie/settimesdotca/actions/runs/32295262333/job/96204985325)), the diagnostics PR itself, so the new probes fired:

```
memory:
  Mem:  15989 total   1189 used   10917 free   47 shared   4276 buff/cache   14800 available
load average:
  (blank — see note)
kernel OOM kills:
  none found (or dmesg not readable)
```

**Memory utilisation was ~7% at the moment wrangler died. 14.8 GB available. No OOM kills.**

## What that settles

The OOM hypothesis is dead. Combined with the four occurrences' shared shape:

| Observation | Conclusion |
|---|---|
| 14.8 GB free, no OOM kills | not resource exhaustion |
| Every request `200 OK` at normal timings to the last one | no degradation before the abort |
| Process gone, port refused in ~0.2 ms | not a hang |
| No error output in 3 of 4 | not a handled error path |
| Always run #3, never #1 or #2 | needs accumulated load |
| Survives wrangler 4.123.0 **and** 4.124.0 | not the version |

**workerd is aborting on its own, on a healthy machine.** That is an upstream bug, not something to tune on our side.

## Caveat, stated rather than glossed

`dmesg` printed *"none found (or dmesg not readable)"* — those two states are conflated in the current probe, so a kernel OOM kill cannot be **fully** excluded on the dmesg evidence alone. It can be excluded on the `free` evidence: nothing OOMs with 14.8 GB available and 7% used. Worth splitting those cases in the probe so the next run is unambiguous.

## Next step

This is now a workerd bug report, and it has a clean reproduction shape:

> `wrangler pages dev` serving a static SPA + D1-backed API dies silently on the **third** consecutive Lighthouse pass, mid-asset-serving, with no error output, on an otherwise idle 16 GB runner.

Before filing upstream, worth capturing: the exact workerd version (`1.20260815.1` with wrangler 4.124.0), whether it reproduces with `--log-level debug`, and whether a plain `wrangler dev` (no Pages) shows it too.

## Not the answer

Reducing `numberOfRuns` to 2 would hide it — the crash needs the accumulated load of runs #1 and #2 to appear. That trades a visible defect for a weaker measurement.

**Comment by BreakableHoodie** [comment]
## Diagnosed: workerd aborts itself. Not OOM, not contention, not the version.

#887's diagnostics caught it on run [32295262333](https://github.com/BreakableHoodie/settimesdotca/actions/runs/32295262333):

```
[wrangler:info] GET / 200 OK (4ms)

✘ [ERROR]                        ← wrangler's own crash handler, EMPTY body
  If you think this is a bug then please create an issue at
  https://github.com/cloudflare/workers-sdk/issues/new/choose

[wrangler:info] GET /assets/index-B7bcQPWv.js 200 OK (31ms)   ← still serving
[wrangler:info] GET /assets/calendar-days-B7zv-wfc.js 200 OK (115ms)
🪵  Logs were written to "/home/runner/.config/.wrangler/logs/wrangler-2026-08-19_19-51-25_719.log"
```

Then, at failure time:

```
listeners on :8788:   none
wrangler/workerd:     none running
HTTP probe:           status=000  time=0.000166s   ← refused instantly, not hung
```

Every remaining hypothesis is now ruled out **from the same run**:

| Hypothesis | Evidence | Verdict |
|---|---|---|
| Kernel OOM kill | `kernel OOM kills: none found`; 14800 MB available of 15989 | ✗ |
| Runner contention | load average 1.63 | ✗ |
| Hang / deadlock | connection **refused** in 0.166 ms, process gone | ✗ — abort, not hang |
| wrangler version | fails on both 4.123.0 and 4.124.0 | ✗ |

Note the ordering: the `[ERROR]` fires, wrangler keeps serving ~9 more requests successfully, and only then does the process disappear. So the error and the death are not the same instant.

### Why we still can't name the cause

Wrangler prints its error body as an **empty string** to stdout. `/tmp/wrangler.log` is only our stdout redirect, so it carries the same blank. The real detail goes to the file wrangler names on the way out — `~/.config/.wrangler/logs/wrangler-<ts>.log` — which nothing was capturing.

#890 captures it. The next occurrence should print the actual reason.

### Next

1. #890 lands → next occurrence yields the stack.
2. With that, file upstream at `cloudflare/workers-sdk` — wrangler's own banner asks for exactly this.
3. Separately worth considering: the gate has no resilience to this today. One abort on run 3 of 3 fails the whole job even though runs 1 and 2 were clean. A wrangler restart + single retry would decouple our CI from an upstream crash we do not control.

**Comment by BreakableHoodie** [comment]
## Root cause captured — it is `ProxyController`, and it is upstream

#890 landed and paid off on its first occurrence: run [32369906113](https://github.com/BreakableHoodie/settimesdotca/actions/runs/32369906113) (PR #894). The stack the console printed as an empty `[ERROR]` is in wrangler's own log file:

```
--- 2026-08-20T12:40:02.675Z error
✘ [ERROR]                       ← still empty here, as always

--- 2026-08-20T12:40:02.676Z debug
Error
    at castErrorCause                        (wrangler-dist/cli.js:179798:20)
    at ProxyController2.emitErrorEvent       (wrangler-dist/cli.js:325599:20)
    at ProxyController2.onProxyWorkerMessage (wrangler-dist/cli.js:325476:18)
    at PROXY_CONTROLLER                      (wrangler-dist/cli.js:325203:24)
    at process.processTicksAndRejections
    at async #handleLoopbackCustomFetchService (miniflare/dist/src/index.js:111478:22)
    at async #handleLoopback                   (miniflare/dist/src/index.js:111709:20)
```

And wrangler's own telemetry confirms it treated this as fatal:

```json
"event": "wrangler command errored",
"wranglerVersion": "4.124.0",
"sanitizedCommand": "pages dev",
"durationMs": 32155,
"isCI": true
```

### What this means

miniflare's loopback custom-fetch service delivers a message to wrangler's `ProxyController`, which emits an error event carrying an `Error` with **no message**. wrangler treats that as a command error and exits — taking the dev server with it, ~32 s after start, mid-Lighthouse-run. Chrome then hits `chrome-error://chromewebdata/` and Lighthouse reports `CHROME_INTERSTITIAL_ERROR`.

The empty message is itself part of the bug: `castErrorCause` produced an `Error` with nothing in it, which is why four occurrences told us nothing.

### Everything else stays ruled out

Confirmed again in this run by the #887 probes: memory fine, load fine, no kernel OOM kill, connection **refused** (not hung), and it fails on both 4.123.0 and 4.124.0.

### Not caused by PR #894

Worth stating since this occurrence landed on a fixture PR: #894 adds a seeded event. The signature is identical to the four prior occurrences, all on unrelated branches, and the failure is the server disappearing rather than any score moving.

### Next

Ready to file upstream at `cloudflare/workers-sdk` — wrangler's own banner asks for exactly this, and we now have a version, a command, a full stack, and a reproduction rate (~1 run in N under `lhci`'s 3 navigations).

Mitigation on our side remains #891, and this strengthens the case for it: the abort is upstream and not ours to fix, so the gate should tolerate it rather than fail a PR that changed nothing relevant.

**Comment by BreakableHoodie** [comment]
## Filed upstream — and it was already known: cloudflare/workers-sdk#14926

Not a new bug. [workers-sdk#14926](https://github.com/cloudflare/workers-sdk/issues/14926) is the canonical report, and a commenter there names our stack verbatim — `castErrorCause → emitErrorEvent → onProxyWorkerMessage → #handleLoopbackCustomFetchService`, empty `✘ [ERROR]`. Five people have consolidated reproductions into it rather than open duplicates, so [we added ours](https://github.com/cloudflare/workers-sdk/issues/14926#issuecomment-5356146622) rather than filing a sixth.

### The actual defect

Since miniflare `4.20260722.0`, miniflare auto-restarts `workerd` after a post-startup crash and exposes an opt-in `unsafeHandleRuntimeRestart` hook. **Wrangler does not implement that hook.** Its `ProxyController` keeps pointing at the dead runtime, the in-flight request fails, and `emitErrorEvent` treats a *recoverable* error as fatal and exits the dev server.

So the empty `Error` is not the cause — it is a recoverable runtime blip that wrangler mishandles into a process exit.

### What our report added

- **Still present on 4.124.0** — one minor newer than the previous latest report (4.123.0).
- **A non-Playwright consumer.** Every prior report is a browser E2E suite with multiple workers; ours is `lhci` doing **three sequential navigations** of one page. So the trigger needs neither parallelism nor a request storm.
- **Resource exhaustion ruled out with numbers** (14800 MB free, load 1.63, no OOM kill, refused in 0.166 ms), which the thread did not yet have.

### There IS a workaround, and unusually, it is available to us

The documented workaround is pinning `wrangler@4.113.0` (the last release before the regression). A commenter notes it is unavailable to any project whose `compatibility_date` is newer than 2026-07-28 — **ours is `2025-10-08`**, so the pin would work here.

**I do not recommend taking it.** Going back 11 minor versions to dodge a bug that only affects the local dev server — never production — costs more than it saves, and it would fight Dependabot continuously.

### Recommendation

**#891 (retry the Lighthouse step after restarting wrangler) is the right mitigation**, and this evidence strengthens it: the abort is upstream, unfixed across at least eleven releases, and not ours to fix. The gate should tolerate a vanished dev server rather than fail PRs that changed nothing relevant — as it just did to #894, which passed on a plain re-run of the identical commit.

Keeping this issue open to track the upstream fix landing, at which point the mitigation can be reconsidered.
